# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: https://codysherman.com
  # Contact: /contact
  # Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
  - /css/nameless.css

# scripts loaded in the end of the body
scripts:
  - /js/nameless.js
